# Generated by Django 3.0.7 on 2020-06-11 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AREA_PROFESIONAL',
            fields=[
                ('nombre_area', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PROCEDIMIENTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procedimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RECURSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PROFESIONAL',
            fields=[
                ('identificador_medico', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=150)),
                ('apellido1', models.CharField(default='', max_length=150)),
                ('apellido2', models.CharField(blank=True, default='', max_length=150)),
                ('edad', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgimp.AREA_PROFESIONAL')),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=150)),
                ('apellido1', models.CharField(default='', max_length=150)),
                ('apellido2', models.CharField(blank=True, default='', max_length=150)),
                ('edad', models.IntegerField()),
                ('fecha_inclusion', models.DateField(default=django.utils.timezone.now)),
                ('diagnostico', models.CharField(max_length=150)),
                ('actividad_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgimp.ACTIVIDAD', verbose_name='Actividad asociada a un paciente')),
                ('procedimiento_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgimp.PROCEDIMIENTOS', verbose_name='tipo de procedimiento asociado a un paciente')),
                ('profesional_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgimp.PROFESIONAL', verbose_name='Profesional asociado a un paciente')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgimp.RECURSO', verbose_name='tipo de recuerso profesional asociado a una actividad'),
        ),
    ]
